### ISSUE TITLE
Gambit: does not pass vmtest5

### ISSUE THREAD

**Issue by okuoku** [okuoku/yuni#122]
```
Test: 134/138 passed.

Failed:
    (qq)
    ((floor-quotient 5 -2))
    (qq)
    ((floor-quotient -5 -2))
```

Test disabled: https://github.com/okuoku/yuni/commit/b063980255626037953d16494a72088bc102d025
Yunibase detected: https://github.com/okuoku/yunibase/commit/4217fb2a69ce474264893fa30c2134ff070fe76a

**Comment by lassik** [comment]
@feeley @gambiteer ?

Tests: https://github.com/okuoku/yuni/blob/7726eb4a0126c9585806160321f9e629e2a1ce2b/tests/vm/vmtest5.sps#L123

**Comment by feeley** [comment]
Perhaps I don't understand what is being tested, but Gambit computes the same result as other Scheme systems for `(floor-quotient 5 -2)` and `(floor-quotient -5 -2)`:

```
% gsi
Gambit v4.9.3

> (floor-quotient 5 -2)
-3
> (floor-quotient -5 -2)
2
```

```
% guile
GNU Guile 2.2.7
scheme@(guile-user)> (floor-quotient 5 -2)
$1 = -3
scheme@(guile-user)> (floor-quotient -5 -2)
$2 = 2
```

```
% chibi-scheme 
> (floor-quotient 5 -2)
-3
> (floor-quotient -5 -2)
2
```

**Comment by okuoku** [comment]
Uh, for historical reasons, Yuni has some polyfills for R7RS procedures. For `floor-quotient`,

https://github.com/okuoku/yuni/blob/b063980255626037953d16494a72088bc102d025/lib-compat/gambit-compat-scheme/base.sls#L303

Most of these are not required nowadays, as R7RS support of Gambit has evolved. Thus I have to remove extraneous polyfills.

**Comment by feeley** [comment]
Indeed a quick look at the library indicates that 90% if not more of those procedures are not needed anymore.  For Gambit you might want to disable that library to check which of the unit tests fail, and then add only the procedures that are still needed to pass the tests. Please report back any bugs you find with Gambit's R7RS support.

**Comment by okuoku** [comment]
Migrated to Gambit's R7RS and confirmed it is working (with new test location https://github.com/okuoku/yuni/blob/27e88c2d4832258a4182198e901d35642634ee57/tests/scheme/inexact0.sps#L80 ). CLOSE.
