### ISSUE TITLE
Gambit: SRFI-6 can return reproducible #!eof 

### ISSUE THREAD

**Issue by okuoku** [okuoku/yuni#132]
```scheme
(define p (open-input-string "xxxx"))

(read-string 0 p) ;; => Gambit: #!eof others: ""
```

**Comment by lassik** [comment]
R7RS **read-string**:

> Reads the next k characters, or as many as are available before the end of file, from the textual input port into a newly allocated string in left-to-right order and returns the string. **If no characters are available before the end of file, an end-of-file object is returned.**

It would seem Gambit has the correct semantics. Though implementing those semantics is slightly more tricky than returning `""`.

**Comment by okuoku** [comment]
IMHO we would allow both behaviour but we have to study more on this (as it can be bug on my test code still).

**Comment by okuoku** [comment]
STklos seems just disallow `0` as size. It will allow this kinds of ambiguity...

Reserved `SIBR0012`: https://github.com/okuoku/yuni/commit/a1e000489485186da786a3473cc1e828a72564bb

**Comment by okuoku** [comment]
`SIBR0012`:

https://github.com/okuoku/yuni/commit/a630f7faac5b060481db1f8c06eafad2eab91e6e?short_path=81729ef#diff-81729ef89cff8c5e17dcce53641104650d4e43dd28505bf6fb9a8836342e5f14

**Comment by okuoku** [comment]
Yuni test suite now tests both non-empty and empty port: 

https://github.com/okuoku/yuni/blob/cf50713277f887e5a8160676aec0fe274703154d/tests/sibr/sibr0012gen.sps#L23-L31

https://github.com/okuoku/yuni/commit/cf50713277f887e5a8160676aec0fe274703154d

... and forgot to add Foment here.

https://github.com/okuoku/yuni/commit/6f032613b27e879852005e41cc2e26df985e2c36
