### ISSUE TITLE
SIBR: (eqv? 0.0 -0.0) behaviour

### ISSUE THREAD

**Issue by okuoku** [okuoku/yuni#163]
at https://github.com/okuoku/yunibase/commit/8bcb02f125b0ae80618493b1432622652905b576

Many Scheme implementations do not distinguish `-0.0` and `0.0` with `eqv?`. 

```
--     ERR: DIGAMMA
--     OK : GUILE3
--     OK : SAGITTARIUS
--     OK : CHIBI_SCHEME
--     OK : CHICKEN5_CSI
--     ERR: ICYC
--     OK : FOMENT
--     ERR: GOSH
--     OK : KAWA
--     OK : CHEZ_SCHEME
--     OK : GUILE
--     ERR: IRON_SCHEME
--     OK : RACKET
--     ERR: BIGLOO
--     OK : GSI
--     OK : MIT_SCHEME
--     ERR: S7
--     ERR: SCM
--     ERR: STKLOS
``` 

- `DIGAMMA`, `ICYC` (Cyclone), `BIGLOO`, `S7` and `GOSH` (Gauche) -- do not distinguish
- `SCM` and `IRON_SCHEME` -- it cannot read `-0.0` properly

**Comment by okuoku** [comment]
Reserved: SIBR0013

https://github.com/okuoku/yuni/commit/cd7638cc2c6c5d7174a9ae2ebff3d874ca80a4db

**Comment by okuoku** [comment]
ref: https://github.com/shirok/Gauche/commit/ca136f159390556a2b34dabf279ced88ab6edc89 Gauche adopted R7RS

**Comment by leppie** [comment]
From memory, at some point I did try to implement `-0.0` for IronScheme, I think there were .NET compat errors (possibly not being able to get `eqv?` to work). From my point of view it was better to not support it than have broken behavior.

**Comment by lassik** [comment]
https://doc.scheme.org/surveys/zero/ has a section on negative zero.

More generaly, it would be great to integrate the data from SIBR into Scheme Surveys.

**Comment by okuoku** [comment]
(Now it's at `docs` : https://docs.scheme.org/surveys/zero/ )

**Comment by okuoku** [comment]
Done: https://github.com/okuoku/yuni/commit/c1e06a88dd4d5a700deb0db8f211ec03c61824ff?short_path=5d8e68c#diff-5d8e68ce8bdfde66d54edbbc7788a4e5d2ef5c6f1ccd44fa927c44bab4d251a6
