### ISSUE TITLE
gambit: SRFI-193 broke yuniboot

### ISSUE THREAD

**Issue by okuoku** [okuoku/yuni#164]
It seems `gsi` is now SRFI-193 compliant and broke yuniboot.

**Comment by lassik** [comment]
> It seems `gsi` is now SRFI-193 compliant

Yes, it is.

> and broke yuniboot.

If there's a problem in Gambit's SRFI 193 implementation, we'll fix it.

Possibly relevant: https://github.com/gambit/gambit/issues/707

**Comment by lassik** [comment]
BTW, `gsc -exe` also produces SRFI 193 compliant standalone executables.

**Comment by okuoku** [comment]
Long story short, Yuni requires `(command-line)` should include at least unmodified path to script file and its argument. In other words, it require direct access to C `argv[]` even on the interpreter.

Previously, `gsi` always returned argv content as string list but it's now virtualised to support SRFI-193 -- now it returns `#f` for any `gsi <script-file.sps>` invocations. Thus it's breaking change when `gsi` was used as a script interpreter.

(We try hard to avoid `#!` invocations since we have to run on Win32 as well)

**Comment by lassik** [comment]
Could you use `(script-file)` on Schemes that have SRFI 193? It's intended specifically for that purpose, as `(command-line)` is not reliable. If `(script-file)` is broken, we'll fix it.

**Comment by lassik** [comment]
Gambit is idiosyncratic, in that it requires `#!` at the start of a script to pass command line arguments to that script. (Things have been this way for a long time.) However, the `#!` line doesn't need to be valid; a blank `#!` not followed by any interpreter name will work fine.

**Comment by okuoku** [comment]
Ugh, that worked.. added dummy shebang to make `(command-line)` return value.

Fixed: https://github.com/okuoku/yuni/commit/c72609eeec8bf20e27bcdf3af17f7548977aad5f

**Comment by lassik** [comment]
A shebang is not needed for SRFI 193; it's a Gambit requirement that is unrelated to the SRFI. It seems supporting the SRFI just unearthed the problem.

**Comment by okuoku** [comment]
> It seems supporting the SRFI just unearthed the problem.

Traditional `command-line` on Gambit was not required `#!`; actually, no other languages require shebang to retrieve `argv[]`... SRFI 193 introduced separation to script and command-line and they're a bit off from traditional `command-line`.

Gambit's own document shows how to use `command-line` without `#!`

https://www.iro.umontreal.ca/~gambit/doc/gambit.html#Procedure_command-line

```
$ gsi -:d -e "(pretty-print (command-line))"
("gsi" "-e" "(pretty-print (command-line))")
```

**Comment by lassik** [comment]
Relying on `command-line` without `#!` in Gambit is very brittle. With the 4.9.3 release version:

```
$ cat foo.scm
(write (command-line))
(newline)

$ gsi foo.scm
("gsi" "foo.scm")

$ gsi foo.scm a b c
("gsi" "foo.scm" "a" "b" "c")
*** ERROR IN ##main -- No such file or directory
(load "a")```

So it prepended `gsi` to your script command line, and didn't work if arguments were passed to your script.

RnRS `command-line` is not reliable for pretty much any purpose; that's why SRFI 193 was written.

**Comment by lassik** [comment]
Also important to note that `command-line` has only a superficial connection to C's `argv[]`. SRFI 193 originally included a separate `os-command-line` procedure corresponding to `argv[]` but it was removed because it's impossible to implement portably. It's particularly hard to get `argv[]` on the JVM, and even C Schemes like Gambit will remove some arguments from `argv[]` when making `command-line`. In particular, Gambit removes `-:` runtime options from `command-line`, and has done so for a long time.

**Comment by lassik** [comment]
I agree that the difference with `#!` and no `#!` is confusing. I suggested to Marc that he remove the different handling, but backward compatibility with prior versions of Gambit requires keeping it. It lets you do things like `gsi a.scm b.scm c.scm` to run several scripts in a row, if none of those scripts have a `#!`. (The first script that has `#!` will cause the rest of the command line arguments not to be parsed by Gambit, and the script will receive them verbatim.)

**Comment by okuoku** [comment]
> So it prepended `gsi` to your script command line, and didn't work if arguments were passed to your script.

It's always workaroundable with [explicit `(exit)`](https://github.com/okuoku/yuni/blob/c72609eeec8bf20e27bcdf3af17f7548977aad5f/lib-runtime/selfboot/common/run-program.scm#L53) to prevent interpreters parse specified command-line after script file. IIRC some other Schemes also behaved like that thus Yuni always call `(exit)` inside its script loader.

```scheme
(write (command-line))
(newline)
(exit)
```

**Comment by lassik** [comment]
Wow, you're right! In any case, it worked by accident since `command-line` just returned the system command line (without `-:` runtime options).
