### ISSUE TITLE
Vicare: do not implicitly flush output port on exit()

### ISSUE THREAD

**Issue by okuoku** [okuoku/yuni#24]
Vicare requires
```scheme
(flush-output-port (current-output-port))
```
on exit to get any output from script. Does example on http://marcomaggi.github.io/docs/vicare-scheme.html/using-invoking.html#using-invoking work?

**Comment by marcomaggi** [comment]
Indeed the examples are wrong: they should all end with flushing.  And there is also the problem of handing command line arguments to the script after the ```--``` separator.  I have fixed the documentation in my ```master``` branch.

As a side note: the current code in Vicare's the ```master``` branch has backwards incompatibilities with the latest release; the online documentation is still the one of the latest release.  Sorry for the inconvenience.

**Comment by okuoku** [comment]
Thanks for your answer. CLOSE this since now we know the behaviour is intended.
