### ISSUE TITLE
Gambit: Detect/Allow VC version of gambit 

### ISSUE THREAD

**Issue by okuoku** [okuoku/yuni#71]
Currently, yuni buildsystem prefer GCC variant of Gambit but on Windows, it would be better to use VC version; but we do not know any way to detect whether or not VC version of `gsc` working. Perhaps we have to implement `gsc` version of `compile_file()` function on CMake.

Mysteriously, the project does not provide link to visualc variant of Gambit builds. They can be downloaded from http://www.iro.umontreal.ca/~gambit/download/gambit/v4.8/prebuilt/ .

Workaround: Specify `-DYUNI_GCC=bogus` on configuration time. We don't use `YUNI_GCC` CMake variable directly for now.

**Comment by okuoku** [comment]
It's simply broken/unusable since it depends on modifying super-critical environment variable such as `CINCLUDE`. Installing it using default installer can break other build system.

**Comment by lassik** [comment]
@okuoku A new release of Gambit is coming soon. Fixes can probably still be included in it.

cc @feeley

**Comment by feeley** [comment]
I'm not sure what you want to do, but if you are trying to get the C compiler then you can do this with the `gambuild-C` script/batch file.  Either call `gambuild-C C_COMPILER` from the shell (or just `gambuild-C` to get all the Gambit shell variable settings) or from Gambit you can execute `(with-input-from-process (list path: (path-expand \"~~bin/gambuild-C\") arguments: '(\"C_COMPILER\")) read-line))"`.
